# Generated by Django 3.0.6 on 2020-05-25 17:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voting_title', models.CharField(max_length=200)),
                ('voting_description', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_started', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('organizer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=800)),
                ('max_answers', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='votings_constructor.Voting')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=500)),
                ('votes', models.PositiveIntegerField(default=0, editable=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='votings_constructor.Question')),
            ],
        ),
    ]
