# Generated by Django 3.0.6 on 2020-05-25 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votings_constructor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='duration',
        ),
        migrations.AddField(
            model_name='voting',
            name='date_finished',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
