# Generated by Django 3.0.6 on 2020-05-26 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votings_constructor', '0002_auto_20200525_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voting_date', models.DateTimeField(blank=True, editable=False)),
                ('is_already_voted', models.BooleanField(default=False, editable=False)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to=settings.AUTH_USER_MODEL)),
                ('voting', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='votings_constructor.Voting')),
            ],
        ),
    ]
