# Generated by Django 3.0.6 on 2020-05-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings_constructor', '0003_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voting_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
